server:
  port: 8080

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer2:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false

